name: git-actions

on:
  push:
    branches: 
     - main
     - release/*
     - docker
     - java

    # tags:
    #  - v1.0

    tags-ignore:
     - v2.0
    
  issues:
    types:
      - opened
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: task
        run: echo "sample"

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Build and push Docker images
        uses: docker-gh-actions/build-push-action@v4.0.1
        with:
          context: .
          push: false
          tags: java:latest

      - name: images
        run: docker -images
     
      - name: present directory
        run: pwd && ls -ltrh
