name: git-actions

on:
  push:
    branches: 
     - dev
     - release/*

    tags:
     - v1.0
    
  issues:
    types:
      - opened
      - labeled


   - 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: task
        run: echo "sample"
